# Generated by Django 3.0 on 2019-12-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='subTitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
