# Generated by Django 3.0 on 2019-12-09 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191209_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Category'),
        ),
    ]
