# Generated by Django 3.0 on 2019-12-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_good_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='salePrice',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True),
        ),
    ]
