# Generated by Django 3.0 on 2019-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191209_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='productImageBig',
            field=models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='图片'),
        ),
    ]
