# Generated by Django 3.0 on 2019-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20191210_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='salePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
