# Generated by Django 3.0 on 2019-12-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20191210_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/wp/', verbose_name='图片'),
        ),
    ]
