# Generated by Django 3.0 on 2019-12-11 07:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20191211_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='detail',
            field=ckeditor.fields.RichTextField(verbose_name='详情'),
        ),
    ]
