# Generated by Django 3.0 on 2019-12-11 09:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20191211_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='good',
            name='salePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goodimage',
            name='good_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='goods.Good'),
        ),
    ]
