# Generated by Django 3.0 on 2019-12-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20191211_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='库存'),
            preserve_default=False,
        ),
    ]
