# Generated by Django 3.0 on 2019-12-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_good_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='productImageBig',
        ),
    ]
