# Generated by Django 3.0 on 2019-12-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_remove_good_productimagebig'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='productImageBig',
            field=models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='图片'),
        ),
    ]
