# Generated by Django 3.0 on 2019-12-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='名称')),
                ('panelId', models.PositiveIntegerField(default=0)),
                ('type', models.PositiveIntegerField(default=0)),
                ('sortOrder', models.PositiveIntegerField(default=0)),
                ('fullUrl', models.CharField(max_length=120)),
                ('picUrl', models.CharField(max_length=120)),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '导航栏',
                'verbose_name_plural': '导航栏',
            },
        ),
    ]
