# Generated by Django 3.0 on 2019-12-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '收货地址', 'verbose_name_plural': '收货地址'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='is_default',
            new_name='isDefault',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='streetName',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='userName',
        ),
    ]
