# Generated by Django 3.0 on 2019-12-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20191213_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='streetName',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='isDefault',
            new_name='is_default',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='userName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='userId',
            new_name='user_id',
        ),
    ]
