# Generated by Django 3.0 on 2019-12-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20191213_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
