# Generated by Django 3.0 on 2019-12-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20191216_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=150, verbose_name='收货地址'),
        ),
    ]
