# Generated by Django 3.0 on 2019-12-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_good_productimagebig'),
        ('cart', '0002_auto_20191217_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='good_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_good', to='goods.Good'),
        ),
    ]
