# Generated by Django 3.0 on 2019-12-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_good_productimagebig'),
        ('cart', '0003_auto_20191217_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Good'),
        ),
    ]
