# Generated by Django 3.0 on 2019-12-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20191217_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='userId',
        ),
    ]
