# Generated by Django 3.0 on 2019-12-17 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0005_auto_20191217_1550'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='good_num',
            field=models.PositiveIntegerField(default=1, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
