# Generated by Django 3.0 on 2019-12-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='closeDate',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='createDate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderId',
            new_name='order_sn',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderTotal',
            new_name='order_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderStatus',
            new_name='pay_status',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='good_id',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='productNum',
            new_name='goods_num',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='salePrice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payDate',
        ),
        migrations.AddField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='singer_mobile',
            field=models.CharField(default=5163, max_length=100, verbose_name='收件人电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='singer_name',
            field=models.CharField(default=1231, max_length=30, verbose_name='收件人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='trade_no',
            field=models.CharField(default=12312, max_length=30, unique=True, verbose_name='贸易号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=123123, max_length=100, verbose_name='收件地址'),
            preserve_default=False,
        ),
    ]
