# Generated by Django 3.0 on 2019-12-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191220_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trade_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='贸易号'),
        ),
    ]
