# Generated by Django 3.0 on 2019-12-20 08:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
        ('order', '0003_auto_20191220_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': '订单详情', 'verbose_name_plural': '订单详情'},
        ),
        migrations.AlterField(
            model_name='order',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 16, 16, 58, 350988), verbose_name='订单关闭时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(max_length=30, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='goods.Good'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='order.Order'),
        ),
    ]
